# Generated by Django 4.0 on 2023-04-13 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataFlow', '0004_alter_project_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='postal_address',
        ),
        migrations.RemoveField(
            model_name='project',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='postcode',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='town',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataFlow.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='job_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
