# Generated by Django 4.1 on 2023-04-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataFlow', '0007_rename_project_address_project_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='image',
        ),
        migrations.AddField(
            model_name='data',
            name='cover',
            field=models.ImageField(default='images/default', null=True, upload_to='images/cover'),
        ),
        migrations.AddField(
            model_name='data',
            name='images',
            field=models.ImageField(null=True, upload_to='images/gallery'),
        ),
    ]
