# Generated by Django 4.1 on 2023-04-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataFlow', '0009_remove_data_cover_remove_data_images_data_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='images/cover'),
        ),
    ]
